---
title: Identifying Priority Conservation Areas in the Florida Everglades for Mangrove Habitat
subtitle: Final Project, ENV 872
author: Isaac Benaka, Hanna Bliska, and Caroline Rowley
date: Fall 2022
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
#setwd("~/Desktop/BenakaBliskaRowley_ENV872_EDA_FinalProject")
getwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(scales)
library(cowplot)
library(trend)
library(zoo)
library(Kendall)
library(sf)
library(mapview)
library(agricolae)

# Set your ggplot theme
my_theme <- theme_classic(base_size=12) + theme(
  axis.text=element_text(color="black"), 
  legend.position="right")
theme_set(my_theme)

# Load your datasets
FCE.mean.sea.levels <- read.csv("./Data/Raw/FCE_KeyWestStation_MeanSeaLevels.csv",
                                stringsAsFactors = TRUE)
FCE.site.coordinates <- read.csv("./Data/Raw/FCE_LTER_site_coordinates.csv",
                                 stringsAsFactors = TRUE)
FCE.nutrients.data <- read.csv("./Data/Raw/LT_ND_Grahl_002.csv",
                               stringsAsFactors = TRUE)
FCE.sawgrass.data <- read.csv("./Data/Raw/LT_PP_Grahl_001.csv",
                              stringsAsFactors = TRUE)
FCE.tree.data <- read.csv("./Data/Raw/LT_PP_Rivera_002.csv",
                          stringsAsFactors = TRUE)
mangrove.sf <- st_read("./Data/Spatial/Mangrove_Habitat_in_Florida/Mangrove_Habitat_in_Florida.shp")
park.boundary <- st_read("./Data/Spatial/park/nps_boundary.shp") %>% filter(UNIT_NAME == "Everglades National Park")
# Project spatial data to UTM 17N
mangrove.utm <- st_transform(mangrove.sf,32617)
park.utm <- st_transform(park.boundary,32617)

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 
```{r}
# Crop mangrove shapefile to Everglades National Park boundary.
mangrove.area <- mangrove.utm[park.utm,] %>% group_by(SOURCEDATE)
# Generate map of mangrove habitat in Everglades National Park.
mapview(mangrove.area, color = "green", col.regions = "dark green", alpha.regions = .4) + mapview(park.boundary, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0)
```



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
