---
title: Identifying Priority Conservation Areas in the Florida Everglades for Mangrove Habitat
subtitle: Final Project, ENV 872
author: Isaac Benaka, Hanna Bliska, and Caroline Rowley
date: Fall 2022
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
#setwd("~/Desktop/BenakaBliskaRowley_ENV872_EDA_FinalProject")
getwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(scales)
library(cowplot)
library(trend)
library(zoo)
library(Kendall)
library(sf)
library(mapview)
library(agricolae)

# Set your ggplot theme
my_theme <- theme_classic(base_size=12) + theme(
  axis.text=element_text(color="black"), 
  legend.position="right")
theme_set(my_theme)

# Load your datasets
FCE.site.coordinates <- read.csv("./Data/Raw/FCE_LTER_site_coordinates.csv")
FCE.nutrients.data <- read.csv("./Data/Raw/FCE_LTER_Nutrients.csv",
                               stringsAsFactors = TRUE)
FCE.tree.data <- read.csv("./Data/Raw/FCE_LTER_Mangroves.csv",
                          stringsAsFactors = TRUE)
inat.birds <- read.csv("./Data/Raw/inaturalist_birds.csv",
                       stringsAsFactors = TRUE)
inat.reptiles <- read.csv("./Data/Raw/inaturalist_reptiles2.csv",
                          stringsAsFactors = TRUE)
inat.mammals <- read.csv("./Data/Raw/inaturalist_mammals.csv",
                         stringsAsFactors = TRUE)  


mangrove.sf <- st_read("./Data/Spatial/Mangrove_Habitat_in_Florida/Mangrove_Habitat_in_Florida.shp")
park.boundary <- st_read("./Data/Spatial/park/nps_boundary.shp") %>% filter(UNIT_NAME == "Everglades National Park")

# Project spatial data to UTM 17N
mangrove.utm <- st_transform(mangrove.sf,32617)
park.utm <- st_transform(park.boundary,32617)

```

# Data Wrangling
```{r, renaming the columns for the data sets}
#renaming column names and removing repeated header row

colnames(FCE.nutrients.data) <- c(
  "SITE_NAME", "DATE", "TIME", "Salinity", "TN", "TP",
  "TOC", "NH4", "NandN", "NO2", "SRP", "DOC", "NO3")
FCE.nutrients.data=FCE.nutrients.data[-1,]

colnames(FCE.sawgrass.data) <- c(
  "SITE_NAME", "DATE", "Sawgrass_AG_Biomass", "Sawgrass_AG_Biomass_STD",
  "Sawgrass_Culm_Density", "Sawgrass_Culm_Density_STD") 
FCE.sawgrass.data=FCE.sawgrass.data[-1,]

colnames(FCE.site.coordinates) <- c(
  "SITE", "Latitude (Decimal Degrees)", "Longitude (Decimal Degrees)",
  "Latitude (Degrees, minutes)", "Longitude (Degrees, minutes)",
  "Northing (UTM)", "Easting (UTM)")
FCE.site.coordinates=FCE.site.coordinates[-1,]

colnames(FCE.tree.data) <- c(
  "SITE", "DATE", "Plot_ID", "Tree_TagNumber",
  "Species.Tree", "Tree_DBH", "Tree_Height")
FCE.tree.data=FCE.tree.data[-1,]

#wrangling the inaturalist data sets to have the same columns
inat.birds <- inat.birds %>% 
  select(observed_on, latitude, longitude, scientific_name, common_name, iconic_taxon_name, taxon_id, taxon_order_name, taxon_genus_name)

inat.reptiles <- inat.reptiles %>% 
  select(observed_on, latitude, longitude, scientific_name, common_name, iconic_taxon_name, taxon_id, taxon_order_name, taxon_genus_name)

inat.mammals <- inat.mammals %>% 
  select(observed_on, latitude, longitude, scientific_name, common_name, iconic_taxon_name, taxon_id, taxon_order_name, taxon_genus_name)


inat.all <- rbind(inat.birds, inat.mammals, inat.reptiles)


```

```{r, formatting data sets}
#formatting date columns
FCE.nutrients.data$DATE <- as.Date(FCE.nutrients.data$DATE, format="%Y-%m-%d")
FCE.sawgrass.data$DATE <- as.Date(FCE.sawgrass.data$DATE, format="%Y-%m-%d")
FCE.tree.data$DATE <- as.Date(FCE.tree.data$DATE, format = "%Y-%m-%d")
inat.all$observed_on <- as.Date(inat.all$observed_on, format("%Y-%m-%d"))

#formatting numeric values
FCE.nutrients.data$TP <- as.numeric(FCE.nutrients.data$TP)
FCE.nutrients.data$TN <- as.numeric(FCE.nutrients.data$TN)
FCE.tree.data$Tree_DBH <- as.numeric(FCE.tree.data$Tree_DBH)
FCE.tree.data$Tree_Height <- as.numeric(FCE.tree.data$Tree_Height)

#wrangling site coordinates data frame to have matching sites
FCE.site.coordinates$SITE <- as.character(FCE.site.coordinates$SITE) 
#convert to character
FCE.site.coordinates$SITE <- gsub('\\s+', '', FCE.site.coordinates$SITE) 
#remove spaces from SITE codes to join to other datasets
FCE.site.coordinates$SITE <- as.factor(FCE.site.coordinates$SITE) 
#convert back to factor
  
```

```{r, wrangling nutrients data set for mean P and N for each year}
FCE.phos.yearly.data <- FCE.nutrients.data %>%
  select(SITE_NAME, DATE, TP) %>% #selecting variables of interest
  mutate(YEAR=year(DATE)) %>% #creating year column
  group_by(YEAR) %>% #grouping by year
  summarise(MEAN_TP=mean(TP)) #averaging the TP for each year

#saving as processed data frame
write.csv(FCE.phos.yearly.data, row.names = FALSE, file= "./Data/Processed/FCE.phos.yearly.data.csv")
  
FCE.nitro.yearly.data <- FCE.nutrients.data %>%
  select(SITE_NAME, DATE, TN) %>% #selecting variables of interest
  mutate(YEAR=year(DATE)) %>% #creating year column
  group_by(YEAR) %>% #grouping by year
  summarise(MEAN_TN=mean(TN))  #averaging the TN for each year

#saving as a processed data frame
write.csv(FCE.nitro.yearly.data, row.names = FALSE, file= "./Data/Processed/FCE.nitro.yearly.data.csv")
  
```

```{r, wranging nutrients data for mean P and N for each month}
#monthly phosphorus averages
FCE.phos.monthly.data <- FCE.nutrients.data %>%
  select(SITE_NAME, DATE, TP) %>%
  mutate(month = month(DATE)) %>% #adding month column
  mutate(year = year(DATE)) %>% #adding a year column
  group_by(year, month) %>% #grouping by year and month
  summarise(MEAN_TP=mean(TP)) #averaging the TP for each month of the year

FCE.phos.monthly.data <- FCE.phos.monthly.data %>%
  mutate("Date"=my(paste0(month,"-",year))) #creating a new date column
  #observations are for the first of the month

Months <- as.data.frame(seq(
  as.Date("2001-05-01"), as.Date("2021-12-01"),"months")) 
#creating a data frame of monthly dates from May 2001 to December 2021
#will ultimately allow us to identify months that do not have observations
#and then interpolate those at a later point

colnames(Months) <- c("Date") #renaming column name

FCE.phos.monthly.data <- left_join(
  Months, FCE.phos.monthly.data, by = c("Date"))
#joining data frames so that there is an observation for 
#each month of the year from May 2001 to December 2021

#saving as a processed data frame
write.csv(FCE.phos.monthly.data, row.names = FALSE, file= "./Data/Processed/FCE.phos.monthly.data.csv")
  
#nitrogen 
FCE.nitro.monthly.data <- FCE.nutrients.data %>%
  select(SITE_NAME, DATE, TN) %>%
  mutate(month = month(DATE)) %>% #adding month column
  mutate(year = year(DATE)) %>% #adding a year column
  group_by(year, month) %>% #grouping by year and month
  summarise(MEAN_TN=mean(TN)) #averaging the TN for each month of the year

FCE.nitro.monthly.data <- FCE.nitro.monthly.data %>%
  mutate("Date"=my(paste0(month,"-",year))) #creating a new date column
  #observations are for the first of the month

FCE.nitro.monthly.data <- left_join(
  Months, FCE.nitro.monthly.data, by = c("Date"))
#joining data frames so that there is an observation for 
#each month of the year from May 2001 to December 2021

#saving as a processed data frame
write.csv(FCE.nitro.monthly.data, row.names = FALSE, file= "./Data/Processed/FCE.phos.monthly.data.csv")
  
```

```{r, wrangling nutrients data set for site differences}
FCE.site.nutrient.data <- FCE.nutrients.data %>%
  select(SITE_NAME, DATE, TP, TN) #selecting variables 
#of interest for site comparisons

#saving as a processed data frame
write.csv(FCE.site.nutrient.data, row.names = FALSE, file= "./Data/Processed/FCE.phos.monthly.data.csv")

```

```{r, wrangling inaturalist data into counts by year}
inat.processed <- inat.all %>% 
   mutate(YEAR=year(observed_on)) %>% 
  filter(scientific_name=="Calidris canutus"| scientific_name=="Charadrius melodus"|scientific_name=="Mycteria americana"| scientific_name=="Rostrhamus sociabilis plumbeus"| scientific_name=="Sterna dougallii"| scientific_name== "Haliaeetus leucocephalus" | #filtering protected birds
         
          scientific_name=="Puma concolor couguar"| scientific_name=="Trichechus manatus" |scientific_name=="Trichechus manatus latirostris" |#filtering protected mammals and raccoon
           
           scientific_name == "Alligator mississippiensis" |scientific_name=="Crocodylus acutus" | scientific_name == "Gopherus polyphemus" | scientific_name=="Drymarchon couperi"| scientific_name=="Caretta caretta"|  scientific_name == "Chelonia mydas"|  #filtering for protected reptiles

scientific_name == "Python bivittatus"|scientific_name== "Dasypus novemcinctus") %>%  #filtering for invasive species
filter(YEAR > '2000-01-01')


#grouping species data by year counts
inat.yearcount <- inat.processed %>% 
  mutate(species = scientific_name) %>%
  filter(YEAR > '2000-01-01') %>% 
  group_by(YEAR, species) %>% 
  summarise(scientific_name=n())

#visualizing year data
animal.plot <- ggplot(inat.yearcount) +
  geom_line(aes(x = YEAR, y = scientific_name, color = species))
print(animal.plot)

#converting to spatial data
inat.spatial <- inat.processed %>% 
  st_as_sf(coords = c('longitude', 'latitude'), crs=4326)
inat.utm <- st_transform(inat.spatial, 4326)

#visualizing spatial data
mapview(inat.spatial)

```

```{r, changing site coordinates to spatial data frame}
site.locations.sf <- st_as_sf(
  FCE.site.coordinates, coords=c(
    'Longitude (Decimal Degrees)', 
    'Latitude (Decimal Degrees)'),crs=4326)
#creating spatial data frame
#specifying Longitude as x and Latitude as y
#using crs 4326

mapview(site.locations.sf) #confirming locations of sites

```

```{r, adding site coordinates to the nutrient data set}
site.locations.nutrients.sf <-
  merge(x=site.locations.sf, 
        y=FCE.site.nutrient.data,
        by.x="SITE",
        by.y="SITE_NAME")
#joining the site locations spatial data frames
#to the sites with nutrient data using merge

```

```{r, wrangling for wood density and agb}

R.trees <- st_as_sf(FCE.tree.data.sites, coords = c("Longitude (Decimal Degrees)","Latitude (Decimal Degrees)"), crs=4326) %>%
  filter(Species.Tree=="R") %>%
  mutate(getWoodDensity(genus = "Rhizophora", species = "mangle")) %>%
  select(DATE, SITE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry)

R.trees <- merge(x=R.trees, y=FCE.site.coordinates, by="SITE", all.x = TRUE)
R.trees$`Latitude (Decimal Degrees)` <- as.numeric(R.trees$`Latitude (Decimal Degrees)`)
R.trees$`Longitude (Decimal Degrees)` <- as.numeric(R.trees$`Longitude (Decimal Degrees)`)
  
R.trees.coordinates <- cbind(R.trees$`Longitude (Decimal Degrees)`, R.trees$`Latitude (Decimal Degrees)`)

R.trees <- R.trees %>%
  mutate(computeAGB(R.trees$Tree_DBH, R.trees$meanWD, coord = R.trees.coordinates)) %>% #computes the above ground biomass in metric tons
  rename(AGB = `computeAGB(R.trees$Tree_DBH, R.trees$meanWD, coord = R.trees.coordinates)`)
R.trees <- R.trees %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry, AGB)

L.trees <- st_as_sf(FCE.tree.data.sites, coords = c("Longitude (Decimal Degrees)","Latitude (Decimal Degrees)"), crs=4326) %>%
  filter(Species.Tree=="L") %>%
  mutate(getWoodDensity(genus = "Laguncularia", species = "racemosa")) %>%
  select(DATE, SITE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry)

L.trees <- merge(x=L.trees, y=FCE.site.coordinates, by="SITE", all.x = TRUE)
L.trees$`Latitude (Decimal Degrees)` <- as.numeric(L.trees$`Latitude (Decimal Degrees)`)
L.trees$`Longitude (Decimal Degrees)` <- as.numeric(L.trees$`Longitude (Decimal Degrees)`)
  
L.trees.coordinates <- cbind(L.trees$`Longitude (Decimal Degrees)`, L.trees$`Latitude (Decimal Degrees)`)

L.trees <- L.trees %>%
  mutate(computeAGB(L.trees$Tree_DBH, L.trees$meanWD, coord = L.trees.coordinates)) %>% #computes the above ground biomass in metric tons
  rename(AGB = `computeAGB(L.trees$Tree_DBH, L.trees$meanWD, coord = L.trees.coordinates)`)
L.trees <- L.trees %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry, AGB)

A.trees <- st_as_sf(FCE.tree.data.sites, coords = c("Longitude (Decimal Degrees)","Latitude (Decimal Degrees)"), crs=4326) %>%
  filter(Species.Tree=="A") %>%
  mutate(getWoodDensity(genus = "Avicennia", species = "germinans")) %>%
  select(DATE, SITE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry)

A.trees <- merge(x=A.trees, y=FCE.site.coordinates, by="SITE", all.x = TRUE)
A.trees$`Latitude (Decimal Degrees)` <- as.numeric(A.trees$`Latitude (Decimal Degrees)`)
A.trees$`Longitude (Decimal Degrees)` <- as.numeric(A.trees$`Longitude (Decimal Degrees)`)
  
A.trees.coordinates <- cbind(A.trees$`Longitude (Decimal Degrees)`, A.trees$`Latitude (Decimal Degrees)`)

A.trees <- A.trees %>%
  mutate(computeAGB(A.trees$Tree_DBH, A.trees$meanWD, coord = A.trees.coordinates)) %>% #computes the above ground biomass in metric tons
  rename(AGB = `computeAGB(A.trees$Tree_DBH, A.trees$meanWD, coord = A.trees.coordinates)`)
A.trees <- A.trees %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry, AGB)

C.trees <- st_as_sf(FCE.tree.data.sites, coords = c("Longitude (Decimal Degrees)","Latitude (Decimal Degrees)"), crs=4326) %>%
  filter(Species.Tree=="C") %>%
  mutate(meanWD = rep(0.69)) %>% #wood density for Conacarpus erectus derived from...
  select(DATE, SITE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry)

C.trees <- merge(x=C.trees, y=FCE.site.coordinates, by="SITE", all.x = TRUE)
C.trees$`Latitude (Decimal Degrees)` <- as.numeric(C.trees$`Latitude (Decimal Degrees)`)
C.trees$`Longitude (Decimal Degrees)` <- as.numeric(C.trees$`Longitude (Decimal Degrees)`)
  
C.trees.coordinates <- cbind(C.trees$`Longitude (Decimal Degrees)`, C.trees$`Latitude (Decimal Degrees)`)

C.trees <- C.trees %>%
  mutate(computeAGB(C.trees$Tree_DBH, C.trees$meanWD, coord = C.trees.coordinates)) %>% #computes the above ground biomass in metric tons
  rename(AGB = `computeAGB(C.trees$Tree_DBH, C.trees$meanWD, coord = C.trees.coordinates)`)
C.trees <- C.trees %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height, meanWD, geometry, AGB)

treeAGB <- bind_rows(A.trees, C.trees, L.trees, R.trees) %>%
  filter(SITE != "TS/Ph8") %>%
  mutate(YEAR = year(DATE))

siteAGB <- treeAGB %>%
  group_by(DATE) %>%
  summarise(meanAGB=mean(AGB)) #issue with two dates showing NA means when values are available to average.

ggplot(siteAGB, aes(x=DATE,y=meanAGB))+
  geom_point()+
  geom_smooth(method=lm)

```

```{r, wrangling into site dataframes}
Years <- as.data.frame(seq(2000,2019,1))

colnames(Years) <- c("YEAR")


treesSRS4 <- treeAGB %>%
  filter(SITE == "SRS4") %>%
  group_by(YEAR) %>%
  summarise(meanAGB = mean(AGB))
treesSRS4 <- left_join(
  Years, treesSRS4, by = c("YEAR"))  


treesSRS5 <- treeAGB %>%
  filter(SITE == "SRS5") %>%
  group_by(YEAR) %>%
  summarise(meanAGB = mean(AGB))
treesSRS5 <- left_join(
  Years, treesSRS5, by = c("YEAR"))

treesSRS6 <- treeAGB %>%
  filter(SITE == "SRS6") %>%
  group_by(YEAR) %>%
  summarise(meanAGB = mean(AGB))
treesSRS6 <- left_join(
  Years, treesSRS6, by = c("YEAR"))

```


```{r, wrangling and plotting DBH tree data by species}
#DBH for Conacarpus erectus
C.trees <- FCE.tree.data %>%
  select(DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="C") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(C.trees, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm")
#DBH for Avicennia germinans
A.trees <- FCE.tree.data %>%
  select(DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="A") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(A.trees, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm")
#DBH for Laguncularia racemosa
L.trees <- FCE.tree.data %>%
  select(DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="L") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(L.trees, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm")
#DBH for Rhizophora mangle
R.trees <- FCE.tree.data %>%
  select(DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="R") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(R.trees, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm")

```

```{r, compare DBH of tree species by site}

#DBH of species in SRS4
C.trees.SRS4 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="C", SITE == "SRS4") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
C.SRS4.plot <- ggplot(C.trees.SRS4, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Conacarpus erectus", y="Mean DBH (cm)")
  

L.trees.SRS4 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="L", SITE == "SRS4") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
L.SRS4plot <- ggplot(L.trees.SRS4, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Laguncularia racemosa", y="Mean DBH (cm)")

R.trees.SRS4 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="R", SITE == "SRS4") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
R.SRS4.plot <- ggplot(R.trees.SRS4, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Rhizophora mangle", y="Mean DBH (cm)")

#DBH of species in SRS5 (A and L increasing, R flat)
A.trees.SRS5 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="A", SITE == "SRS5") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
A.SRS5.plot <- ggplot(A.trees.SRS5, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method=lm, se=F)+
  labs(title="Avicennia germinans", y="Mean DBH (cm)")

L.trees.SRS5 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="L", SITE == "SRS5") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
L.SRS5.plot <- ggplot(L.trees.SRS5, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Laguncularia racemosa", y="Mean DBH (cm)")

R.trees.SRS5 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="R", SITE == "SRS5") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
R.SRS5.plot <- ggplot(R.trees.SRS5, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Rhizophora mangle", y="Mean DBH (cm)")

#DBH of species in SRS6 (all decreasing)
A.trees.SRS6 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="A", SITE == "SRS6") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
A.SRS6plot <- ggplot(A.trees.SRS6, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Avicennia germinans", y="Mean DBH (cm)")

L.trees.SRS6 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="L", SITE == "SRS6") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
L.SRS6plot <- ggplot(L.trees.SRS6, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Laguncularia racemosa", y="Mean DBH (cm)")

R.trees.SRS6 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="R", SITE=="SRS6") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
R.SRS6.plot <- ggplot(R.trees.SRS6, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Rhizophora mangle", y="Mean DBH (cm)")

#DBH of species in TS/Ph8 (all increasing)
C.trees.TSPh8 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="C", SITE == "TS/Ph8") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(C.trees.TSPh8, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Conacarpus erectus", y="Mean DBH (cm)")
  
L.trees.TSPh8 <- FCE.tree.data %>%
  select(SITE, DATE, Species.Tree, Tree_DBH, Tree_Height) %>%
  filter(Species.Tree=="L", SITE == "TS/Ph8") %>%
  group_by(DATE) %>%
  summarise(mean.DBH=mean(Tree_DBH))
ggplot(L.trees.TSPh8, aes(x=DATE,y=mean.DBH))+
  geom_point()+
  geom_smooth(method = "lm", se=F)+
  labs(title="Laguncularia racemosa", y="Mean DBH (cm)")


```


```{r, wrangling tree data for geospatial analysis}
#FCE.tree.data <- FCE.tree.data$Species.Tree %>% recode(FCE.tree.data$Species.Tree, C="Conacarpus erectus", A="Avicennia germinans", L="Laguncularia racemosa", R="Rhizophora mangle")

FCE.tree.data.sites <- merge(x=FCE.tree.data, y=FCE.site.coordinates, by="SITE", all.x = TRUE)

#make sf dataframe from tree data (not showing over basemap correctly)
tree.data.sf <- st_as_sf(FCE.tree.data.sites, coords = c("Longitude (Decimal Degrees)","Latitude (Decimal Degrees)"), crs=4326) %>% 
  group_by(SITE, DATE) %>%
  summarize(
    meanDBH=mean(Tree_DBH)
  )
mapview(tree.data.sf)

#split tree data into separate tree types for spatial analysis

```


