---
title: Identifying Priority Conservation Areas in the Florida Everglades for Mangrove Habitat
subtitle: Final Project, ENV 872
author: Isaac Benaka, Hanna Bliska, and Caroline Rowley
date: Fall 2022
output:
 pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
#setwd("~/Desktop/BenakaBliskaRowley_ENV872_EDA_FinalProject")
getwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(scales)
library(cowplot)
library(trend)
library(zoo)
library(Kendall)
library(sf)
library(mapview)
library(agricolae)

# Set your ggplot theme
my_theme <- theme_classic(base_size=12) + theme(
  axis.text=element_text(color="black"), 
  legend.position="right")
theme_set(my_theme)

# Load your datasets
FCE.site.coordinates <- read.csv("./Data/Raw/FCE_LTER_site_coordinates.csv")
FCE.nutrients.data <- read.csv("./Data/Raw/FCE_LTER_Nutrients.csv",
                               stringsAsFactors = TRUE)
FCE.tree.data <- read.csv("./Data/Raw/FCE_LTER_Mangroves.csv",
                          stringsAsFactors = TRUE)
inat.birds <- read.csv("./Data/Raw/inaturalist_birds.csv",
                       stringsAsFactors = TRUE)
inat.reptiles <- read.csv("./Data/Raw/inaturalist_reptiles2.csv",
                          stringsAsFactors = TRUE)
inat.mammals <- read.csv("./Data/Raw/inaturalist_mammals.csv",
                         stringsAsFactors = TRUE)  

```

# Exploratory Analysis 

```{r, site analysis for nutrients}
#running anova to see if particular sites have more nitrogen
nitrogen.site.anova <- aov(data=FCE.site.nutrient.data, 
                           TN ~ SITE_NAME)
summary(nitrogen.site.anova)

#evaluating groups
nitrogen.site.anova.groups <- HSD.test(nitrogen.site.anova, 
                                       "SITE_NAME", 
                                       group = TRUE)
#printing groups
nitrogen.site.anova.groups

#results indicate that there are three groups of sites: a, b, and c.

#running anova to see if particular sites have more phosphorus
phos.site.anova <- aov(data=FCE.site.nutrient.data, 
                           TP ~ SITE_NAME)
summary(phos.site.anova)

#evaluating groups
phos.site.anova.groups <- HSD.test(phos.site.anova, 
                                       "SITE_NAME", 
                                       group = TRUE)
#printing groups
phos.site.anova.groups

#results indicate that there are four groups of sites: a, b, c, d. There is only one site that is in group a and only one site in group b. 
```

```{r, visualization of ANOVA analysis for nutrients}
anova.nitro.site.plot <- ggplot(FCE.site.nutrient.data, aes(x=SITE_NAME, y=TN)) +
  geom_boxplot()+
  xlab(expression("Site Name")) +
  ylab(expression("Total Nitrogen (mcmol/L)")) +
  ggtitle(expression("Total Nitrogen Measurements for Sites"),
          subtitle="Florida Coastal Everglades") +
  annotate("text", x = 1, y = 1500, label = "bc") +
  annotate("text", x = 2, y = 1500, label = "bc") +
  annotate("text", x = 3, y = 1500, label = "a") +
  annotate("text", x = 4, y = 1500, label = "a") +
  annotate("text", x = 5, y = 1500, label = "a") +
  annotate("text", x = 6, y = 1500, label = "ab") +
  annotate("text", x = 7, y = 1500, label = "b") +
  annotate("text", x = 8, y = 1500, label = "c")
anova.nitro.site.plot

anova.phos.site.plot <- ggplot(FCE.site.nutrient.data, aes(x=SITE_NAME, y=TP)) +
  geom_boxplot()+
  xlab(expression("Site Name")) +
  ylab(expression("Total Phosphorus (mcmol/L)")) +
  ggtitle(expression("Total Phosphorus Measurements for Sites"),
          subtitle="Florida Coastal Everglades") +
  annotate("text", x = 1, y = 200, label = "d") +
  annotate("text", x = 2, y = 200, label = "d") +
  annotate("text", x = 3, y = 200, label = "cd") +
  annotate("text", x = 4, y = 200, label = "d") +
  annotate("text", x = 5, y = 200, label = "cd") +
  annotate("text", x = 6, y = 200, label = "c") +
  annotate("text", x = 7, y = 200, label = "b") +
  annotate("text", x = 8, y = 200, label = "a")
anova.phos.site.plot
```


```{r, time series analysis for phosphorus}
FCE.phos.monthly.data$MEAN_TP <- 
  na.approx(FCE.phos.monthly.data$MEAN_TP) #using`na.approx`
#to fill in missing monthly data

FCE.phos.monthly.ts <- ts(
  FCE.phos.monthly.data$MEAN_TP, 
  start=c(2001,5), end=c(2021,12),frequency=12) 
#generating time series object
#monthly measurements, using 12

FCE.phos.monthly.ts.decomposed <- stl(
  FCE.phos.monthly.ts, s.window = "periodic") 
#decomposing daily time series
plot(FCE.phos.monthly.ts.decomposed) #plotting components

#running mann kendall
FCE.phos.monthly.ts.trend <- MannKendall(FCE.phos.monthly.ts) 
#using `MannKendall` for trend analysis
summary(FCE.phos.monthly.ts.trend) #summary

```

```{r, time series analysis for nitrogen}
FCE.nitro.monthly.data$MEAN_TN <- 
  na.approx(FCE.nitro.monthly.data$MEAN_TN) #using`na.approx`
#to fill in missing monthly data

FCE.nitro.monthly.ts <- ts(
  FCE.nitro.monthly.data$MEAN_TN, 
  start=c(2001,5), end=c(2021,12),frequency=12) 
#generating time series object
#monthly measurements, using 12

FCE.nitro.monthly.ts.decomposed <- stl(
  FCE.nitro.monthly.ts, s.window = "periodic") 
#decomposing daily time series
plot(FCE.nitro.monthly.ts.decomposed) #plotting components

#running mann kendall
FCE.nitro.monthly.ts.trend <- MannKendall(FCE.nitro.monthly.ts) 
#using `MannKendall` for trend analysis
summary(FCE.nitro.monthly.ts.trend) #summary
```

```{r, visualizations of time series results for nutrients}
plot.mean.monthly.phos <- ggplot(
  FCE.phos.monthly.data, aes(
    x=Date, y=MEAN_TP)) + #setting axes
  geom_point() + #generating scatter plot
  geom_line() + #generating line plot
  scale_x_date(date_breaks="1 year", labels=date_format("%m-%Y")) +
  #using `scale_x_date` to generate a break every 6 months
  #labels to show month-date-year
  theme(axis.text.x=element_text(angle=60, hjust=1)) + 
  #angle for the day-month-year labels
  xlab(expression("Date")) + #setting x axis label
  ylab(expression ("Mean Monthly Phosphorus Levels (mcmol/L)")) +
#setting y axis label
  geom_smooth(method=lm, se = FALSE, color="red") + #adding linear trend
  ggtitle(expression("Mean Monthly Phosphorus Levels"),
          subtitle="Florida Coastal Everglades")
print(plot.mean.monthly.phos) #printing plot

plot.mean.monthly.nitro <- ggplot(
  FCE.nitro.monthly.data, aes(
    x=Date, y=MEAN_TN)) + #setting axes
  geom_point() + #generating scatter plot
  geom_line() + #generating line plot
  scale_x_date(date_breaks="1 year", labels=date_format("%m-%Y")) +
  #using `scale_x_date` to generate a break every 6 months
  #labels to show month-date-year
  theme(axis.text.x=element_text(angle=60, hjust=1)) + 
  #angle for the day-month-year labels
  xlab(expression("Date")) + #setting x axis label
  ylab(expression ("Mean Monthly Nitrogen Levels (mcmol/L)")) +
#setting y axis label
  geom_smooth(method=lm, se = FALSE, color="red") + #adding linear trend
  ggtitle(expression("Mean Monthly Nitrogen Levels"),
          subtitle="Florida Coastal Everglades")
print(plot.mean.monthly.nitro) #printing plot

```


```{r, plots of mangrove DBH over time by site}
# SRS4
plot_grid(R.SRS4.plot, C.SRS4.plot, L.SRS4plot,  ncol=1)

#SRS5
plot_grid(R.SRS5.plot, A.SRS5.plot, L.SRS5.plot, ncol=1)

#SRS6
plot_grid(R.SRS6.plot, A.SRS6plot, L.SRS6plot, ncol=1)

```

```{r, mapping the iNaturalist data}
#filtering for endangered birds
inat.woodstork <- inat.utm %>% 
  filter(scientific_name %in% c("Mycteria americana"))
inat.snailkite <- inat.utm %>% 
  filter(scientific_name %in% c("Rostrhamus sociabilis plumbeus"))
#plotting endangered birds
endangered.bird.map <- mapview(inat.woodstork, col.regions = "peru" , layer.name = "Wood Stork Observations 2000-2022")+
  mapview(inat.snailkite, col.regions = "cyan3", layer.name= "Everglade Snail Kite Observations 2000-2022")
print(endangered.bird.map)


#filtering for threatened birds
inat.baldeagle <-inat.utm %>% 
  filter(scientific_name %in% c("Haliaeetus leucocephalus"))
inat.pipingplover <-inat.utm %>% 
  filter(scientific_name %in% c("Charadrius melodus"))
inat.redknot <-inat.utm %>% 
  filter(scientific_name %in% c("Calidris canutus"))
inat.roseatetern <-inat.utm %>% 
  filter(scientific_name %in% c("Sterna dougallii"))
#plotting threatened birds
threatened.bird.map <- mapview(inat.pipingplover, col.regions = "seagreen2", layer.name = "Piping Plover Observations 2000-2022")+
  mapview(inat.baldeagle, col.regions = "mediumorchid2", layer.name = "Bald Eagle Observations 2000-2002")+
  mapview(inat.redknot, col.regions = "orange1", layer.name = "Red Knot Observations 2000-2022")+
  mapview(inat.roseatetern, col.regions = "turquoise2", layer.name= "Roseate Tern Observations 2000-2022")+
  mapview(park.utm, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0, layer.name = "Everglades National Park Boundary")
print(threatened.bird.map)

#filtering for protected reptiles
inat.greenseaturtle <- inat.utm %>% 
  filter(scientific_name%in% c("Chelonia mydas"))
inat.loggerhead <- inat.utm %>% 
  filter(scientific_name %in% c("Caretta caretta"))
inat.tortoise <-inat.utm %>% 
  filter(scientific_name%in%c("Gopherus polyphemus"))
inat.indigosnake <- inat.utm %>% 
  filter(scientific_name%in% c("Drymarchon couperi"))
#plotting protected reptiles
protected.reptiles.map <- mapview(inat.greenseaturtle, col.regions="mediumorchid2", layer.name= "Green Sea Turtle (Endangered) Observations 2000-2022")+
  mapview(inat.loggerhead, col.regions="seagreen2", layer.name = "Loggerhead Sea Turtle (Threatened) Observations 2000-2022")+
    mapview(inat.tortoise, col.regions="turquoise2", layer.name="Gopher Tortoise (proposed Threatened Candidate) Observations 2000-2022")+
  mapview(inat.indigosnake, col.regions= "peru", layer.name="Eastern Indigo Snake (Threatened) Observations 2000-2022")+
  mapview(park.utm, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0, layer.name = "Everglades National Park Boundary")
print(protected.reptiles.map)

#filtering for crocodiles and alligators
inat.crocodile <-inat.utm %>% 
  filter(scientific_name%in% c("Crocodylus acutus"))
inat.alligator <-inat.utm %>% 
  filter(scientific_name%in%c("Alligator mississippiensis"))

#plotting threatened reptiles
alligator.and.croc.map <- mapview(inat.crocodile, col.regions="seagreen2", layer.name = "American Crocodile Observations 2000-2022")+
  mapview(inat.alligator, col.regions="peru", layer.name = "American Alligator (Proposed Threatened) Observations 2000-2022")+
  mapview(park.utm, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0, layer.name = "Everglades National Park Boundary")
print(alligator.and.croc.map)

#filtering for protected mammals
inat.cougar <-inat.utm %>% 
  filter(scientific_name %in% c("Puma concolor couguar"))
inat.florida.manatee <- inat.utm %>% 
  filter(scientific_name%in%c("Trichechus manatus latirostris"))
inat.west.indian.manatee <- inat.utm %>% 
  filter(scientific_name%in%c("Trichechus manatus"))
#plotting protected mammals
protected.mammal.map <- mapview(inat.cougar, col.regions="peru", layer.name= "Florida Panther (Endangered) Observations 2000-2022")+
  mapview(inat.florida.manatee, col.regions="mediumorchid2", layer.name= "Florida Manatee (Threatened) Observations 2000-2022")+
mapview(inat.west.indian.manatee, col.regions="seagreen2", layer.name= "West Indian Manatee (Threatened) Observations 2000-2022")+
  mapview(park.utm, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0, layer.name = "Everglades National Park Boundary")
print(protected.mammal.map)

#filtering for invasive species
inat.python <-inat.utm %>% 
  filter(scientific_name%in% c("Python bivittatus"))
inat.armadillo <- inat.utm %>% 
  filter(scientific_name%in% c("Dasypus novemcinctus"))
inat.knight.anole <-inat.utm %>% 
  filter(scientific_name%in% c("Anolis equestris"))
inat.brown.anole <-inat.utm %>% 
  filter(scientific_name%in% c("Anolis sagrei"))
inat.tokay <-inat.utm %>% 
  filter(scientific_name%in% c("Gekko gecko"))
inat.indopacific.gecko <-inat.utm %>% 
  filter(scientific_name%in% c("Hemidactylus garnotii"))
inat.house.gecko <-inat.utm %>% 
  filter(scientific_name%in% c("Hemidactylus mabouia"))
inat.iguana <-inat.utm %>% 
  filter(scientific_name%in% c("Iguana iguana"))
inat.brahminy.blind.snake <-inat.utm %>% 
  filter(scientific_name%in% c("Indotyphlops braminus"))
#plotting invasive map
invasive.map<- mapview(inat.python, col.regions ="peru", layer.name= "Burmese Python (Invasive) Observations 2000-2022")+
  mapview(inat.armadillo, col.regions ="mediumorchid2", layer.name= "Nine Banded Armadillo (Invasive) Observations 2000-2022")+
  mapview(inat.knight.anole, col.regions ="seagreen2", layer.name= "Knight Anole (Invasive) Observations 2000-2022")+
  mapview(inat.brown.anole, col.regions ="turquoise2", layer.name= "Brown Anole (Invasive) Observations 2000-2022")+
  mapview(inat.tokay, col.regions ="orange1", layer.name= "Tokay Gecko (Invasive) Observations 2000-2022")+
  mapview(inat.indopacific.gecko, col.regions ="cyan3", layer.name= "Indopacific Gecko (Invasive) Observations 2000-2022")+
  mapview(inat.house.gecko, col.regions ="deeppink2", layer.name= "Tropical House Gecko (Invasive) Observations 2000-2022")+
  mapview(inat.iguana, col.regions ="burlywood3", layer.name= "Common Iguana (Invasive) Observations 2000-2022")+
  mapview(inat.brahminy.blind.snake, col.regions ="olivedrab2", layer.name= "Brahimy Blind Snake (Invasive) Observations 2000-2022")+
  mapview(park.utm, color = 'black', lwd = 2, col.regions = "black", alpha.regions = 0, layer.name = "Everglades National Park Boundary")

print(invasive.map)

```

