---
title: Identifying Priority Conservation Areas in the Florida Everglades for Mangrove
  Habitat
author: "Isaac Benaka, Hanna Bliska, and Caroline Rowley"
date: "Fall 2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
subtitle: Final Project, ENV 872
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
library(tidyverse)
library(lubridate)
library(scales)
library(cowplot)
library(trend)
library(zoo)
library(Kendall)
library(sf)
library(mapview)
library(agricolae)

# Set your ggplot theme
my_theme <- theme_classic(base_size=12) + theme(
  axis.text=element_text(color="black"), 
  legend.position="right")
theme_set(my_theme)

# Load your datasets
FCE.site.coordinates <- read.csv("./Data/Raw/FCE_LTER_site_coordinates.csv",
                                 stringsAsFactors = TRUE)
FCE.nutrients.data <- read.csv("./Data/Raw/FCE_LTER_Nutrients.csv",
                               stringsAsFactors = TRUE)
FCE.tree.data <- read.csv("./Data/Raw/FCE_LTER_Mangroves.csv",
                          stringsAsFactors = TRUE)
inat.birds <- read.csv("./Data/Raw/inaturalist_birds.csv",
                       stringsAsFactors = TRUE)
inat.reptiles <- read.csv("./Data/Raw/inaturalist_reptiles2.csv",
                          stringsAsFactors = TRUE)
inat.mammals <- read.csv("./Data/Raw/inaturalist_mammals.csv",
                         stringsAsFactors = TRUE)  
```

The final spatial dataset for Everglades National Park boundary (`park.boundary`) is as follows:

| Variable   | Units            | Range         | Mean    |
| ---------- | ---------------- | ------------- | ------- |
| UNIT_NAME  | N/A              | N/A           | N/A     |
| geometry   | x,y coordinates  | N/A           | N/A     |

# Data Exploration

```{r, exploring LTER data sets}
#exploring nutrients data set
head(FCE.nutrients.data)
summary(FCE.nutrients.data)
str(FCE.nutrients.data)

#exploring tree data set
head(FCE.tree.data)
summary(FCE.tree.data)
str(FCE.tree.data)

#exploring sawgrass data set
head(FCE.sawgrass.data)
summary(FCE.sawgrass.data)
str(FCE.sawgrass.data)

#exploring site coordinates data set
head(FCE.site.coordinates)
summary(FCE.site.coordinates)
str(FCE.site.coordinates)

#exploring mean sea levels data set
head(FCE.mean.sea.levels)
summary(FCE.mean.sea.levels)
str(FCE.mean.sea.levels)

#exploring the iNaturalist mammal data set
head(inat.mammals)
summary(inat.mammals)
str(inat.mammals)

#exploring the iNaturalist bird data set
head(inat.birds)
summary(inat.birds)
str(inat.birds)

#exploring the iNaturalist reptile data set
head(inat.reptiles)
summary(inat.reptiles)
str(inat.reptiles)
```

```{r, initial visualizations of nutrient data}
phos.plot <- ggplot(FCE.phos.yearly.data, aes(x=YEAR, y=MEAN_TP)) +
  geom_point()+
  geom_smooth(method=lm, se=FALSE, color="blue")+
  xlab(expression("Date")) +
  ylab(expression("Mean Total Phosphorus (mcmol/L)")) +
  ggtitle(expression("Mean Total Phosphorus Measurements"),
          subtitle="Florida Coastal Everglades")
phos.plot
  
nitro.plot <- ggplot(FCE.nitro.yearly.data, aes(x=YEAR, y=MEAN_TN)) +
  geom_point()+
  geom_smooth(method=lm, se=FALSE, color="blue") +
  xlab(expression("Date")) +
  ylab(expression("Mean Total Nitrogen (mcmol/L)")) +
  ggtitle(expression("Mean Total Nitrogen Measurements"),
          subtitle="Florida Coastal Everglades")
nitro.plot

nitro.site.plot <- ggplot(FCE.site.nutrient.data, aes(x=SITE_NAME, y=TN)) +
  geom_boxplot()+
  xlab(expression("Site Name")) +
  ylab(expression("Total Nitrogen (mcmol/L)")) +
  ggtitle(expression("Total Nitrogen Measurements for Sites"),
          subtitle="Florida Coastal Everglades")
nitro.site.plot

phos.site.plot <- ggplot(FCE.site.nutrient.data, aes(x=SITE_NAME, y=TP)) +
  geom_boxplot()+
  xlab(expression("Site Name")) +
  ylab(expression("Total Phosphorus (mcmol/L)")) +
  ggtitle(expression("Total Phosphorus Measurements for Sites"),
          subtitle="Florida Coastal Everglades")
phos.site.plot
```

```{r, visualizing monitoring sites with high N and P}
mapview(site.locations.nutrients.sf, zcol="TN")
mapview(site.locations.nutrients.sf, zcol="TP")
```


